

export const AUTH_LOGIN_START = 'AUTH_LOGIN_START'
export const AUTH_LOGIN_SUCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'


export const AUTH_SIGNUP_START = 'AUTH_SIGNUP_START'
export const AUTH_SIGNUP_SUCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL'


export const GET_ALLBOOKS_START = 'GET_ALLBOOKS_START'
export const GET_ALLBOOKS_SUCESS = 'GET_ALLBOOKS_SUCCESS'
export const GET_ALLBOOKS_FAIL = 'GET_ALLBOOKS_FAIL'


export const GET_ONEBOOKS_START = 'GET_ONEBOOKS_START'
export const GET_ONEBOOKS_SUCESS = 'GET_ONEBOOKS_SUCCESS'
export const GET_ONEBOOKS_FAIL = 'GET_ONEBOOKS_FAIL'


export const GET_AUTHOR_BOOKS_START = 'GET_AUTHOR_BOOKS_START'
export const GET_AUTHOR_BOOKS_SUCESS = 'GET_AUTHOR_BOOKS_SUCCESS'
export const GET_AUTHOR_BOOKS_FAIL = 'GET_AUTHOR_BOOKS_FAIL'

export const POST_AUTHOR_BOOKS_START = 'POST_AUTHOR_BOOKS_START'
export const POST_AUTHOR_BOOKS_SUCESS = 'POST_AUTHOR_BOOKS_SUCCESS'
export const POST_AUTHOR_BOOKS_FAIL = 'POST_AUTHOR_BOOKS_FAIL'

export const DELETE_AUTHOR_BOOKS_START = 'DELETE_AUTHOR_BOOKS_START'
export const DELETE_AUTHOR_BOOKS_SUCESS = 'DELETE_AUTHOR_BOOKS_SUCCESS'
export const DELETE_AUTHOR_BOOKS_FAIL = 'DELETE_AUTHOR_BOOKS_FAIL'

export const EDIT_AUTHOR_BOOKS_START = 'EDIT_AUTHOR_BOOKS_START'
export const EDIT_AUTHOR_BOOKS_SUCESS = 'EDIT_AUTHOR_BOOKS_SUCCESS'
export const EDIT_AUTHOR_BOOKS_FAIL = 'EDIT_AUTHOR_BOOKS_FAIL'

export const GET_PAGE_START = 'GET_PAGE_START'
export const GET_PAGE_SUCESS = 'GET_PAGE_SUCCESS'
export const GET_PAGE_FAIL = 'GET_PAGE_FAIL'


export const CREATE_PAGE_START = 'CREATE_PAGE_START'
export const CREATE_PAGE_SUCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_FAIL = 'CREATE_PAGE_FAIL'

export const EDIT_PAGE_START = 'EDIT_PAGE_START'
export const EDIT_PAGE_SUCESS = 'EDIT_PAGE_SUCCESS'
export const EDIT_PAGE_FAIL = 'EDIT_PAGE_FAIL'


export const DELETE_PAGE_START = 'DELETE_PAGE_START'
export const DELETE_PAGE_SUCESS = 'DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_FAIL = 'DELETE_PAGE_FAIL'